// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: copyfrom.go

package postgresdriver

import (
	"context"
)

// iteratorForInsertServiceRecords implements pgx.CopyFromSource.
type iteratorForInsertServiceRecords struct {
	rows                 []InsertServiceRecordsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertServiceRecords) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertServiceRecords) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].NodePublicKey,
		r.rows[0].PoktChainID,
		r.rows[0].SessionKey,
		r.rows[0].RequestID,
		r.rows[0].PortalRegionName,
		r.rows[0].Latency,
		r.rows[0].Tickets,
		r.rows[0].Result,
		r.rows[0].Available,
		r.rows[0].Successes,
		r.rows[0].Failures,
		r.rows[0].P90SuccessLatency,
		r.rows[0].MedianSuccessLatency,
		r.rows[0].WeightedSuccessLatency,
		r.rows[0].SuccessRate,
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
	}, nil
}

func (r iteratorForInsertServiceRecords) Err() error {
	return nil
}

func (q *Queries) InsertServiceRecords(ctx context.Context, arg []InsertServiceRecordsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"service_record"}, []string{"node_public_key", "pokt_chain_id", "session_key", "request_id", "portal_region_name", "latency", "tickets", "result", "available", "successes", "failures", "p90_success_latency", "median_success_latency", "weighted_success_latency", "success_rate", "created_at", "updated_at"}, &iteratorForInsertServiceRecords{rows: arg})
}
