name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'

env:
  PROJECT_ID: portal-gb-prod
  REPOSITORY: transaction-http-db
  IMAGE: transaction-http-db
  REGISTRY: us-central1-docker.pkg.dev

jobs:
  login-build-push:
    name: Docker login, build, and push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.6.0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        token_format: 'access_token'

    - name: Login to GAR
      uses: docker/login-action@v2
      with:
        registry: "${{ env.REGISTRY }}"
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Get tag
      id: get-tag
      run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

    - id: docker-push-tagged
      name: Tag Docker image and push to Google Artifact Registry
      uses: docker/build-push-action@v2
      with:
        build-args: GITHUB_TOKEN=${{ secrets.GH_ACCESS_TOKEN }}
        push: true
        tags: |
            ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ steps.get-tag.outputs.short_ref }}
            ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:latest
